version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'weekly'
      day: 'friday'
    assignees:
      - "sendo-kakeru"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: 'friday'
    assignees:
      - "sendo-kakeru"
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 20
    groups:
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      react-router:
        patterns:
          - react-router
          - '@types/react-router'
          - '@react-router/*'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      radix-ui:
        patterns:
          - 'radix-ui'
          - '@radix-ui/*'
      tailwindcss:
        patterns:
          - tailwindcss
          - '@tailwindcss/*'
      vitest:
        patterns:
          - vitest
          - '@vitest/*'